language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  github_token: $GH_TOKEN
  keep_history: true
  skip_cleanup: true
  on:
    branch: master
  local_dir: public
#参考文档https://docs.travis-ci.com/user/deployment/pages