sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  github_token: $GH_TOKEN
  keep_history: true
  skip_cleanup: true
  target_branch: master
  # source分支存放源文件，master分支为发布的分支。由于最初创建githubpage时选的是个人站点，所以默认发布分支是master
  on:
    branch: source
  local_dir: public
#参考文档https://docs.travis-ci.com/user/deployment/pages